# Automatically generated by pb2py
# fmt: off
import protobuf as p


class LiquidPublicKey(p.MessageType):
    MESSAGE_WIRE_TYPE = 802

    def __init__(
        self,
        pubkey: bytes = None,
    ) -> None:
        self.pubkey = pubkey

    @classmethod
    def get_fields(cls):
        return {
            1: ('pubkey', p.BytesType, 0),
        }
