# Automatically generated by pb2py
# fmt: off
import protobuf as p


class LiquidBlindOutput(p.MessageType):
    MESSAGE_WIRE_TYPE = 801

    def __init__(
        self,
        amount: int = None,
        script_pubkey: bytes = None,
    ) -> None:
        self.amount = amount
        self.script_pubkey = script_pubkey

    @classmethod
    def get_fields(cls):
        return {
            1: ('amount', p.UVarintType, 0),
            2: ('script_pubkey', p.BytesType, 0),
        }
