# Automatically generated by pb2py
# fmt: off
import protobuf as p


class TestOnlyRequest(p.MessageType):
    MESSAGE_WIRE_TYPE = 81

    def __init__(
        self,
        arg1: bytes = None,
    ) -> None:
        self.arg1 = arg1

    @classmethod
    def get_fields(cls):
        return {
            1: ('arg1', p.BytesType, 0),
        }
